// NetMon tarayıcı giriş noktası. Modüller bağımlılık sırasıyla yüklenir.
import "./js/core.js";
import "./js/api.js";
import "./js/auth.js";
import "./js/navigation.js";
import "./js/diagnostics.js";
import "./js/academy.js";
import "./js/purple-team.js";
import "./js/administration.js";
import "./js/dashboard.js";
import "./js/inventory.js";
import "./js/topology.js";
import "./js/topology-details.js";
import "./js/ipam.js";
import "./js/traffic.js";
import "./js/ncm.js";
import "./js/notifications.js";
import "./js/device-experience.js";
import "./js/runtime.js";
